# Generated by Django 5.0.8 on 2024-08-13 01:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20, unique=True)),
                ('hourmeter', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_suntech_hourmeter', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Initial Suntech Hourmeter')),
                ('initial_machine_hourmeter', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Initial Machine Hourmeter')),
                ('worked_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Worked Hours')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('fuel', models.CharField(blank=True, default='DIESEL', max_length=8, null=True, verbose_name='Fuel')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipament', to='api.device')),
            ],
            options={
                'verbose_name_plural': 'Equipaments',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_suntech_hourmeter', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Initial Suntech Hourmeter')),
                ('initial_maintenance_hourmeter', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Initial Maintenance Hourmeter')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Alarme')),
                ('os', models.BooleanField(default=False, verbose_name='Order Service (OS)')),
                ('usage_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tempo de uso (Peça)')),
                ('alarm_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tempo para o próximo alarme')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('equipament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='api.equipament')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
            },
        ),
        migrations.CreateModel(
            name='StopRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hourmeter', models.DecimalField(decimal_places=2, max_digits=20)),
                ('identifier', models.CharField(max_length=255)),
                ('preventive', models.CharField(max_length=255)),
                ('piece_name', models.CharField(max_length=255)),
                ('time_in_maintenance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_records', to='api.equipament')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_records', to='api.maintenance')),
            ],
        ),
        migrations.AddIndex(
            model_name='equipament',
            index=models.Index(fields=['device', 'name'], name='api_equipam_device__b28981_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['equipament'], name='api_mainten_equipam_64f07c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['name'], name='api_mainten_name_77bc80_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['os'], name='api_mainten_os_af85a8_idx'),
        ),
    ]
