# Generated by Django 5.0.8 on 2024-08-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Maintenance', 'verbose_name_plural': 'Maintenances'},
        ),
    ]
